name: Deploy

on:
  push:
    branches:
      - prod

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: CI/CD
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            cd /home/roabella/admin/front/Roabella-Admin-Front
            echo "로아벨라 관리자 Front 경로 진입"
            git pull origin prod
            echo "prod 브랜치 pull"
            sudo fuser -k -n tcp 3000 || true
            echo "기존 3000 포트 실행 중이던 프로세스 확인 후 제거"
            npm run dev
            echo "로아벨라 관리자 페이지 업데이트 반영 실행"